# Generated by Django 5.2.3 on 2025-11-04 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0002_customuser_birth_date_customuser_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermedia',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='usermedia',
            name='file',
            field=models.FileField(upload_to='user_media/', verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='usermedia',
            name='media_type',
            field=models.CharField(choices=[('audio', 'Audio'), ('image', 'Imagen')], max_length=10, verbose_name='Tipo de archivo'),
        ),
    ]
