# Generated by Django 5.2.3 on 2025-11-05 15:36

import django.core.serializers.json
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
                ('ciudad', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('clave_encripcion', models.BinaryField(blank=True, null=True)),
                ('zona_horaria', models.CharField(default='UTC', max_length=50)),
            ],
            options={
                'verbose_name': 'Agencia',
                'verbose_name_plural': 'Agencias',
                'ordering': ['-fecha_registro'],
                'permissions': [('view_dashboard_agencia', 'Puede ver el dashboard de la agencia')],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaAgente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('detalles', models.JSONField(default=dict)),
                ('tarea_celery', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Auditoría de Agente',
                'verbose_name_plural': 'Auditorías de Agentes',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaMonedero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado_anterior', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('estado_posterior', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('metadata', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('tarea_celery', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaRecarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('detalles', models.JSONField(default=dict)),
                ('error', models.TextField(blank=True, null=True)),
                ('tarea_celery', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Auditoría de Recarga',
                'verbose_name_plural': 'Auditorías de Recargas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaRetencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('detalles', models.JSONField(default=dict)),
                ('error', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Auditoría de Retención',
                'verbose_name_plural': 'Auditorías de Retenciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaTransferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('detalles', models.JSONField(default=dict)),
                ('error', models.TextField(blank=True, null=True)),
                ('tarea_celery', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Auditoría de Transferencia',
                'verbose_name_plural': 'Auditorías de Transferencias',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_transferencia_diaria', models.DecimalField(decimal_places=2, default=Decimal('500000.00'), max_digits=12)),
                ('limite_recarga_diaria', models.DecimalField(decimal_places=2, default=Decimal('100000.00'), max_digits=12)),
                ('minimo_transferencia', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=12)),
                ('comision_transferencia_porcentaje', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5)),
                ('comision_transferencia_minima', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=12)),
                ('comision_recarga_agente', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5)),
                ('requiere_verificacion_monto', models.DecimalField(decimal_places=2, default=Decimal('50000.00'), max_digits=12)),
                ('max_intentos_verificacion', models.PositiveIntegerField(default=3)),
                ('max_operaciones_diarias', models.PositiveIntegerField(default=10)),
                ('tiempo_espera_procesamiento', models.PositiveIntegerField(default=30, help_text='Tiempo en segundos para procesamiento asíncrono')),
                ('reintentos_fallidos', models.PositiveIntegerField(default=3)),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuraciones del Sistema',
            },
        ),
        migrations.CreateModel(
            name='DashboardAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Dashboard Principal', max_length=100)),
                ('configuracion', models.JSONField(default=dict)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dashboard de Administración',
                'verbose_name_plural': 'Dashboards de Administración',
            },
        ),
        migrations.CreateModel(
            name='Monedero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('saldo_retenido', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('limite_credito', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('nivel_verificacion', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Monedero',
                'verbose_name_plural': 'Monederos',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TRANSFERENCIA', 'Transferencia'), ('RECARGA', 'Recarga de saldo'), ('ALERTA_SEG', 'Alerta de seguridad'), ('VERIFICACION', 'Verificación requerida'), ('SISTEMA', 'Mensaje del sistema'), ('REPORTE', 'Reporte generado')], max_length=20)),
                ('titulo', models.CharField(max_length=100)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(default=dict)),
                ('importante', models.BooleanField(default=False)),
                ('tarea_celery', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones_Monederos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Recarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('comision_agente', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('monto_neto', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADA', 'Completada'), ('RECHAZADA', 'Rechazada'), ('EN_PROCESO', 'En Proceso')], default='PENDIENTE', max_length=20)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('datos_pago', models.JSONField(default=dict)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_procesamiento', models.DateTimeField(blank=True, null=True)),
                ('tarea_procesamiento', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Recarga de Saldo',
                'verbose_name_plural': 'Recargas de Saldo',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TRANSFERENCIAS', 'Reporte de Transferencias'), ('RECARGAS', 'Reporte de Recargas'), ('AGENTES', 'Reporte de Agentes'), ('USUARIOS', 'Reporte de Usuarios')], max_length=20)),
                ('parametros', models.JSONField(default=dict)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='reportes/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('tarea_celery', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DEBITO', 'Débito'), ('CREDITO', 'Crédito'), ('RETENCION', 'Retención')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('referencia', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADA', 'Completada'), ('FALLIDA', 'Fallida'), ('REVERTIDA', 'Revertida')], default='COMPLETADA', max_length=10)),
                ('metadata', models.JSONField(default=dict)),
                ('relacion_id', models.PositiveIntegerField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='TransaccionRetenida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('LIBERADA', 'Liberada'), ('APLICADA', 'Aplicada'), ('CANCELADA', 'Cancelada')], default='ACTIVA', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('motivo', models.CharField(max_length=255)),
                ('relacion_id', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Transacción Retenida',
                'verbose_name_plural': 'Transacciones Retenidas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('5000.00'))])),
                ('comision', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADA', 'Completada'), ('FALLIDA', 'Fallida'), ('REVERTIDA', 'Revertida'), ('EN_VERIFICACION', 'En Verificación'), ('PROGRAMADA', 'Programada')], default='PENDIENTE', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_procesamiento', models.DateTimeField(blank=True, null=True)),
                ('fecha_programada', models.DateTimeField(blank=True, null=True)),
                ('codigo_verificacion', models.CharField(blank=True, max_length=6, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('tarea_programada', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Transferencia',
                'verbose_name_plural': 'Transferencias',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_agente', models.CharField(max_length=20, unique=True)),
                ('comision_acumulada', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('_pin_operaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('ultima_actividad', models.DateTimeField(blank=True, null=True)),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agentes_asociados', to='monedero.agencia')),
            ],
            options={
                'verbose_name': 'Agente',
                'verbose_name_plural': 'Agentes',
                'ordering': ['-fecha_registro'],
                'permissions': [('procesar_recargas', 'Puede procesar recargas de saldo'), ('view_dashboard_agente', 'Puede ver el dashboard de agente')],
            },
        ),
    ]
