# Generated by Django 5.2.2 on 2025-06-11 21:05

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
                ('ciudad', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('clave_encripcion', models.BinaryField()),
                ('zona_horaria', models.CharField(default='UTC', max_length=50)),
            ],
            options={
                'verbose_name': 'Agencia',
                'verbose_name_plural': 'Agencias',
                'ordering': ['-fecha_registro'],
                'permissions': [('view_dashboard_agencia', 'Puede ver el dashboard de la agencia')],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_transferencia_diaria', models.DecimalField(decimal_places=2, default=Decimal('500000.00'), max_digits=12)),
                ('limite_recarga_diaria', models.DecimalField(decimal_places=2, default=Decimal('100000.00'), max_digits=12)),
                ('minimo_transferencia', models.DecimalField(decimal_places=2, default=Decimal('5000.00'), max_digits=12)),
                ('comision_transferencia_porcentaje', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5)),
                ('comision_transferencia_minima', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=12)),
                ('comision_recarga_agente', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5)),
                ('requiere_verificacion_monto', models.DecimalField(decimal_places=2, default=Decimal('50000.00'), max_digits=12)),
                ('max_intentos_verificacion', models.PositiveIntegerField(default=3)),
                ('max_operaciones_diarias', models.PositiveIntegerField(default=10)),
                ('tiempo_espera_procesamiento', models.PositiveIntegerField(default=30, help_text='Tiempo en segundos para procesamiento asíncrono')),
                ('reintentos_fallidos', models.PositiveIntegerField(default=3)),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuraciones del Sistema',
            },
        ),
        migrations.CreateModel(
            name='DashboardAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Dashboard Principal', max_length=100)),
                ('configuracion', models.JSONField(default=dict)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dashboard de Administración',
                'verbose_name_plural': 'Dashboards de Administración',
            },
        ),
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_agente', models.CharField(max_length=20, unique=True)),
                ('comision_acumulada', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('_pin_operaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('ultima_actividad', models.DateTimeField(blank=True, null=True)),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agentes', to='monedero.agencia')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agente',
                'verbose_name_plural': 'Agentes',
                'ordering': ['-fecha_registro'],
                'permissions': [('procesar_recargas', 'Puede procesar recargas de saldo'), ('view_dashboard_agente', 'Puede ver el dashboard de agente')],
            },
        ),
        migrations.CreateModel(
            name='Monedero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('saldo_retenido', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('limite_credito', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('nivel_verificacion', models.PositiveSmallIntegerField(default=1)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='monedero', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monedero',
                'verbose_name_plural': 'Monederos',
            },
        ),
        migrations.CreateModel(
            name='AuditoriaMonedero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado_anterior', models.JSONField(default=dict)),
                ('estado_posterior', models.JSONField(default=dict)),
                ('metadata', models.JSONField(default=dict)),
                ('tarea_celery', models.CharField(blank=True, max_length=100, null=True)),
                ('monedero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='monedero.monedero')),
            ],
            options={
                'verbose_name': 'Auditoría de Monedero',
                'verbose_name_plural': 'Auditorías de Monederos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TRANSFERENCIA', 'Transferencia'), ('RECARGA', 'Recarga de saldo'), ('ALERTA_SEG', 'Alerta de seguridad'), ('VERIFICACION', 'Verificación requerida'), ('SISTEMA', 'Mensaje del sistema'), ('REPORTE', 'Reporte generado')], max_length=20)),
                ('titulo', models.CharField(max_length=100)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(default=dict)),
                ('importante', models.BooleanField(default=False)),
                ('tarea_celery', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_monedero', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones_Monederos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Recarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('comision_agente', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('monto_neto', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADA', 'Completada'), ('RECHAZADA', 'Rechazada'), ('EN_PROCESO', 'En Proceso')], default='PENDIENTE', max_length=20)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('datos_pago', models.JSONField(default=dict)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_procesamiento', models.DateTimeField(blank=True, null=True)),
                ('tarea_procesamiento', models.CharField(blank=True, max_length=100, null=True)),
                ('agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recargas_procesadas', to='monedero.agente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recargas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recarga de Saldo',
                'verbose_name_plural': 'Recargas de Saldo',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaRecarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('detalles', models.JSONField(default=dict)),
                ('error', models.TextField(blank=True, null=True)),
                ('tarea_celery', models.CharField(blank=True, max_length=100, null=True)),
                ('recarga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='monedero.recarga')),
            ],
            options={
                'verbose_name': 'Auditoría de Recarga',
                'verbose_name_plural': 'Auditorías de Recargas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TRANSFERENCIAS', 'Reporte de Transferencias'), ('RECARGAS', 'Reporte de Recargas'), ('AGENTES', 'Reporte de Agentes'), ('USUARIOS', 'Reporte de Usuarios')], max_length=20)),
                ('parametros', models.JSONField(default=dict)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='reportes/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('tarea_celery', models.CharField(blank=True, max_length=100, null=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DEBITO', 'Débito'), ('CREDITO', 'Crédito'), ('RETENCION', 'Retención')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('referencia', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADA', 'Completada'), ('FALLIDA', 'Fallida'), ('REVERTIDA', 'Revertida')], default='COMPLETADA', max_length=10)),
                ('metadata', models.JSONField(default=dict)),
                ('relacion_id', models.PositiveIntegerField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('relacion_contenido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='TransaccionRetenida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('LIBERADA', 'Liberada'), ('APLICADA', 'Aplicada'), ('CANCELADA', 'Cancelada')], default='ACTIVA', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('motivo', models.CharField(max_length=255)),
                ('relacion_id', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('relacion_contenido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retenciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transacción Retenida',
                'verbose_name_plural': 'Transacciones Retenidas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaRetencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('detalles', models.JSONField(default=dict)),
                ('error', models.TextField(blank=True, null=True)),
                ('retencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='monedero.transaccionretenida')),
            ],
            options={
                'verbose_name': 'Auditoría de Retención',
                'verbose_name_plural': 'Auditorías de Retenciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('5000.00'))])),
                ('comision', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADA', 'Completada'), ('FALLIDA', 'Fallida'), ('REVERTIDA', 'Revertida'), ('EN_VERIFICACION', 'En Verificación'), ('PROGRAMADA', 'Programada')], default='PENDIENTE', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_procesamiento', models.DateTimeField(blank=True, null=True)),
                ('fecha_programada', models.DateTimeField(blank=True, null=True)),
                ('codigo_verificacion', models.CharField(blank=True, max_length=6, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('tarea_programada', models.CharField(blank=True, max_length=100, null=True)),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_enviadas', to=settings.AUTH_USER_MODEL)),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_recibidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transferencia',
                'verbose_name_plural': 'Transferencias',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaTransferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('detalles', models.JSONField(default=dict)),
                ('error', models.TextField(blank=True, null=True)),
                ('tarea_celery', models.CharField(blank=True, max_length=100, null=True)),
                ('transferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='monedero.transferencia')),
            ],
            options={
                'verbose_name': 'Auditoría de Transferencia',
                'verbose_name_plural': 'Auditorías de Transferencias',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaAgente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('detalles', models.JSONField(default=dict)),
                ('tarea_celery', models.CharField(blank=True, max_length=100, null=True)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='monedero.agente')),
            ],
            options={
                'verbose_name': 'Auditoría de Agente',
                'verbose_name_plural': 'Auditorías de Agentes',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['agente', 'accion'], name='monedero_au_agente__d5c6e7_idx'), models.Index(fields=['fecha'], name='monedero_au_fecha_118f81_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='monedero',
            index=models.Index(fields=['usuario'], name='monedero_mo_usuario_3161e2_idx'),
        ),
        migrations.AddIndex(
            model_name='monedero',
            index=models.Index(fields=['saldo'], name='monedero_mo_saldo_b147c3_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriamonedero',
            index=models.Index(fields=['monedero', 'accion'], name='monedero_au_moneder_754193_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriamonedero',
            index=models.Index(fields=['fecha'], name='monedero_au_fecha_48d533_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['usuario', 'leida'], name='monedero_no_usuario_136835_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['tipo', 'fecha'], name='monedero_no_tipo_fb60e4_idx'),
        ),
        migrations.AddIndex(
            model_name='recarga',
            index=models.Index(fields=['usuario', 'estado'], name='monedero_re_usuario_776551_idx'),
        ),
        migrations.AddIndex(
            model_name='recarga',
            index=models.Index(fields=['agente', 'estado'], name='monedero_re_agente__2088fb_idx'),
        ),
        migrations.AddIndex(
            model_name='recarga',
            index=models.Index(fields=['fecha_creacion'], name='monedero_re_fecha_c_93104c_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriarecarga',
            index=models.Index(fields=['recarga', 'accion'], name='monedero_au_recarga_9ffa07_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriarecarga',
            index=models.Index(fields=['fecha'], name='monedero_au_fecha_3125a5_idx'),
        ),
        migrations.AddIndex(
            model_name='transaccion',
            index=models.Index(fields=['usuario', 'tipo'], name='monedero_tr_usuario_9bdd4d_idx'),
        ),
        migrations.AddIndex(
            model_name='transaccion',
            index=models.Index(fields=['referencia'], name='monedero_tr_referen_f7caa9_idx'),
        ),
        migrations.AddIndex(
            model_name='transaccion',
            index=models.Index(fields=['relacion_contenido', 'relacion_id'], name='monedero_tr_relacio_184e06_idx'),
        ),
        migrations.AddIndex(
            model_name='transaccionretenida',
            index=models.Index(fields=['usuario', 'estado'], name='monedero_tr_usuario_7017d5_idx'),
        ),
        migrations.AddIndex(
            model_name='transaccionretenida',
            index=models.Index(fields=['referencia'], name='monedero_tr_referen_aa6a59_idx'),
        ),
        migrations.AddIndex(
            model_name='transaccionretenida',
            index=models.Index(fields=['fecha_expiracion'], name='monedero_tr_fecha_e_5e7b59_idx'),
        ),
        migrations.AddIndex(
            model_name='transaccionretenida',
            index=models.Index(fields=['relacion_contenido', 'relacion_id'], name='monedero_tr_relacio_2d7749_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriaretencion',
            index=models.Index(fields=['retencion', 'accion'], name='monedero_au_retenci_3b72d1_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriaretencion',
            index=models.Index(fields=['fecha'], name='monedero_au_fecha_4920ef_idx'),
        ),
        migrations.AddIndex(
            model_name='transferencia',
            index=models.Index(fields=['emisor', 'estado'], name='monedero_tr_emisor__6d8d4f_idx'),
        ),
        migrations.AddIndex(
            model_name='transferencia',
            index=models.Index(fields=['receptor', 'estado'], name='monedero_tr_recepto_5a8f6c_idx'),
        ),
        migrations.AddIndex(
            model_name='transferencia',
            index=models.Index(fields=['fecha_creacion'], name='monedero_tr_fecha_c_1e009f_idx'),
        ),
        migrations.AddIndex(
            model_name='transferencia',
            index=models.Index(fields=['fecha_programada'], name='monedero_tr_fecha_p_77bceb_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriatransferencia',
            index=models.Index(fields=['transferencia', 'accion'], name='monedero_au_transfe_706925_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriatransferencia',
            index=models.Index(fields=['fecha'], name='monedero_au_fecha_32f1ca_idx'),
        ),
    ]
