# Generated by Django 5.2.3 on 2025-11-05 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('monedero', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agente',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditoriaagente',
            name='agente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='monedero.agente'),
        ),
        migrations.AddField(
            model_name='monedero',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='monedero', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditoriamonedero',
            name='monedero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='monedero.monedero'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_monedero', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recarga',
            name='agente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recargas_procesadas', to='monedero.agente'),
        ),
        migrations.AddField(
            model_name='recarga',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recargas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditoriarecarga',
            name='recarga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='monedero.recarga'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='relacion_contenido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaccionretenida',
            name='relacion_contenido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='transaccionretenida',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retenciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditoriaretencion',
            name='retencion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='monedero.transaccionretenida'),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='emisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_enviadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='receptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_recibidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditoriatransferencia',
            name='transferencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='monedero.transferencia'),
        ),
        migrations.AddIndex(
            model_name='auditoriaagente',
            index=models.Index(fields=['agente', 'accion'], name='monedero_au_agente__d5c6e7_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriaagente',
            index=models.Index(fields=['fecha'], name='monedero_au_fecha_118f81_idx'),
        ),
        migrations.AddIndex(
            model_name='monedero',
            index=models.Index(fields=['usuario'], name='monedero_mo_usuario_3161e2_idx'),
        ),
        migrations.AddIndex(
            model_name='monedero',
            index=models.Index(fields=['saldo'], name='monedero_mo_saldo_b147c3_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriamonedero',
            index=models.Index(fields=['monedero', 'fecha'], name='monedero_au_moneder_b78e28_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriamonedero',
            index=models.Index(condition=models.Q(('estado_posterior__has_key', 'saldo')), fields=['estado_posterior'], name='idx_saldo_posterior'),
        ),
        migrations.AddIndex(
            model_name='auditoriamonedero',
            index=models.Index(condition=models.Q(('estado_anterior__has_key', 'saldo')), fields=['estado_anterior'], name='idx_saldo_anterior'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['usuario', 'leida'], name='monedero_no_usuario_136835_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['tipo', 'fecha'], name='monedero_no_tipo_fb60e4_idx'),
        ),
        migrations.AddIndex(
            model_name='recarga',
            index=models.Index(fields=['usuario', 'estado'], name='monedero_re_usuario_776551_idx'),
        ),
        migrations.AddIndex(
            model_name='recarga',
            index=models.Index(fields=['agente', 'estado'], name='monedero_re_agente__2088fb_idx'),
        ),
        migrations.AddIndex(
            model_name='recarga',
            index=models.Index(fields=['fecha_creacion'], name='monedero_re_fecha_c_93104c_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriarecarga',
            index=models.Index(fields=['recarga', 'accion'], name='monedero_au_recarga_9ffa07_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriarecarga',
            index=models.Index(fields=['fecha'], name='monedero_au_fecha_3125a5_idx'),
        ),
        migrations.AddIndex(
            model_name='transaccion',
            index=models.Index(fields=['usuario', 'tipo'], name='monedero_tr_usuario_9bdd4d_idx'),
        ),
        migrations.AddIndex(
            model_name='transaccion',
            index=models.Index(fields=['referencia'], name='monedero_tr_referen_f7caa9_idx'),
        ),
        migrations.AddIndex(
            model_name='transaccion',
            index=models.Index(fields=['relacion_contenido', 'relacion_id'], name='monedero_tr_relacio_184e06_idx'),
        ),
        migrations.AddIndex(
            model_name='transaccionretenida',
            index=models.Index(fields=['usuario', 'estado'], name='monedero_tr_usuario_7017d5_idx'),
        ),
        migrations.AddIndex(
            model_name='transaccionretenida',
            index=models.Index(fields=['referencia'], name='monedero_tr_referen_aa6a59_idx'),
        ),
        migrations.AddIndex(
            model_name='transaccionretenida',
            index=models.Index(fields=['fecha_expiracion'], name='monedero_tr_fecha_e_5e7b59_idx'),
        ),
        migrations.AddIndex(
            model_name='transaccionretenida',
            index=models.Index(fields=['relacion_contenido', 'relacion_id'], name='monedero_tr_relacio_2d7749_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriaretencion',
            index=models.Index(fields=['retencion', 'accion'], name='monedero_au_retenci_3b72d1_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriaretencion',
            index=models.Index(fields=['fecha'], name='monedero_au_fecha_4920ef_idx'),
        ),
        migrations.AddIndex(
            model_name='transferencia',
            index=models.Index(fields=['emisor', 'estado'], name='monedero_tr_emisor__6d8d4f_idx'),
        ),
        migrations.AddIndex(
            model_name='transferencia',
            index=models.Index(fields=['receptor', 'estado'], name='monedero_tr_recepto_5a8f6c_idx'),
        ),
        migrations.AddIndex(
            model_name='transferencia',
            index=models.Index(fields=['fecha_creacion'], name='monedero_tr_fecha_c_1e009f_idx'),
        ),
        migrations.AddIndex(
            model_name='transferencia',
            index=models.Index(fields=['fecha_programada'], name='monedero_tr_fecha_p_77bceb_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriatransferencia',
            index=models.Index(fields=['transferencia', 'accion'], name='monedero_au_transfe_706925_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriatransferencia',
            index=models.Index(fields=['fecha'], name='monedero_au_fecha_32f1ca_idx'),
        ),
    ]
