# Generated by Django 5.2.2 on 2025-06-11 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monedero', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agente',
            name='agencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agentes_asociados', to='monedero.agencia'),
        ),
    ]
