# Generated by Django 5.2.2 on 2025-06-14 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monedero', '0002_alter_agente_agencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencia',
            name='clave_encripcion',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
