# Generated by Django 5.2.3 on 2025-06-30 20:39

import django.core.serializers.json
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monedero', '0003_alter_agencia_clave_encripcion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditoriamonedero',
            options={'ordering': ['-fecha']},
        ),
        migrations.RemoveIndex(
            model_name='auditoriamonedero',
            name='monedero_au_moneder_754193_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditoriamonedero',
            name='monedero_au_fecha_48d533_idx',
        ),
        migrations.AlterField(
            model_name='auditoriamonedero',
            name='estado_anterior',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='auditoriamonedero',
            name='estado_posterior',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='auditoriamonedero',
            name='metadata',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='minimo_transferencia',
            field=models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=12),
        ),
        migrations.AddIndex(
            model_name='auditoriamonedero',
            index=models.Index(fields=['monedero', 'fecha'], name='monedero_au_moneder_b78e28_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriamonedero',
            index=models.Index(condition=models.Q(('estado_posterior__has_key', 'saldo')), fields=['estado_posterior'], name='idx_saldo_posterior'),
        ),
        migrations.AddIndex(
            model_name='auditoriamonedero',
            index=models.Index(condition=models.Q(('estado_anterior__has_key', 'saldo')), fields=['estado_anterior'], name='idx_saldo_anterior'),
        ),
    ]
