# Generated by Django 5.2.3 on 2025-07-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Duración de la canción en segundos', null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='file',
            field=models.FileField(help_text='Formatos soportados: MP3, WAV, OGG, WEBM (solo audio), M4A. Tamaño máximo: 20MB', upload_to='songs/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.ImageField(blank=True, help_text='Formatos soportados: JPG, PNG, WEBP. Tamaño máximo: 2MB', null=True, upload_to='images/%Y/%m/%d/'),
        ),
    ]
