version: '3.9'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    command: gunicorn djidji1.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend/djidji1:/app
      - media_data:/app/media
      - static_data:/app/static
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://myuser:mypassword@db:5432/mydb
      REDIS_URL: redis://redis:6379

volumes:
  postgres_data:
  media_data:
  static_data:
